### ISSUE TITLE
no matching function for call to 'PCF8574::PCF8574(uint8_t, TwoWire*)'

### ISSUE THREAD

**Issue by ispybadguys** [skybadger/ESP8266_AscomSwitch#1]
I was working on getting this to compile. Is here a specific PCF8574 library that I need to use?

**Comment by skybadger** [comment]
it appears to be this one - from the json 
{
  "name": "PCF8574",
  "keywords": "I2C, PCF8574, PCF8574A, IO, shift, rotate, readButton, toggle, reverse",
  "description": "Arduino library for PCF8574 - 8 channel I2C IO expander, implements shift rotate.",
  "authors":
  [
    {
      "name": "Rob Tillaart",
      "email": "Rob.Tillaart@gmail.com",
      "maintainer": true
    }
  ],
  "repository":
  {
    "type": "git",
    "url": "https://github.com/RobTillaart/PCF8574.git"
  },
  "version": "0.3.2",
  "license": "MIT",
  "frameworks": "arduino",
  "platforms": "*"
}
